In [12]:
import cv2

src = cv2.imread('./Open/t03/1.jpg')
# resized = cv2.resize(src, dsize=(0,0), fx = 0.25, fy = 0.25, interpolation=cv2.INTER_LINEAR)

roi = cv2.selectROI(src)
print('roi =', roi)	# (x 시작 지점, y 시작 지점, width, height)
print(resized.shape)
 
cv2.waitKey()
cv2.destroyAllWindows()

roi = (0, 0, 0, 0)
(756, 1008, 3)


In [60]:
import cv2
import numpy as np

for i in range(1, 31):
    if(i < 10):
        img = cv2.imread('./Open/t0{}/5.jpg'.format(i),0)
    else:
        img = cv2.imread('./Open/t{}/5.jpg'.format(i), 0)
    img = cv2.resize(img, dsize=(0,0), fx = 0.25, fy = 0.25, interpolation=cv2.INTER_LINEAR)
    # img = cv2.medianBlur(img,5)
    cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)
    circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,700,
                                param1=50,param2=30,minRadius=300,maxRadius=400)
    circles = np.uint16(np.around(circles))
    
    if len(circles) == 1:
        x, y, r = circles[0][0]
#         print x, y, r
        mask = np.zeros((img.shape[0],img.shape[1]),dtype=np.uint8)
        cv2.circle(mask,(x,y),r,(255,255,255),-1,8,0)
#         cv2.imwrite(argv[2],mask)
        out = img*mask
        white = 255-mask
        cv2.imwrite('./circles_crop/{}.png'.format(i),out+white)
    
#     for j in circles[0,:]:
#         cv2.circle(cimg,(j[0],j[1]),j[2],(0,255,0),2)
#     cv2.imshow('detected circles',cimg)
#     cv2.imwrite('./circles/{}.png'.format(i), cimg)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [199]:
for i in range(1, 31):
    if(i < 10):
        img = cv2.imread('./Open/t0{}/1.jpg'.format(i),0)
    else:
        img = cv2.imread('./Open/t{}/1.jpg'.format(i), 0)
    img = cv2.resize(img, dsize=(0,0), fx = 0.125, fy = 0.275, interpolation=cv2.INTER_LINEAR)
    h = img.shape[0]
    w = img.shape[1]
    x = int(w/2)
    y = int(h/2)

    img = img[y-int(h/6):y+int(h/6), x-int(w/3):x+int(w/2)]

    cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)
    circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,600,
                                    param1=50,param2=25,minRadius=170,maxRadius=180)
    circles = np.uint16(np.around(circles))
    
    if len(circles) == 1:
        x, y, r = circles[0][0]
#         print x, y, r
        mask = np.zeros((img.shape[0],img.shape[1]),dtype=np.uint8)
        cv2.circle(mask,(x,y),r,(255,255,255),-1,8,0)
#         cv2.imwrite(argv[2],mask)
        out = img*mask
        white = 255-mask
        cv2.imwrite('./circles_crop2/3rd/{}.png'.format(i),out+white)

#     for j in circles[0,:]:
#         cv2.circle(cimg,(j[0],j[1]),j[2],(0,255,0),2)

#     cv2.imshow('detected circles',cimg)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [18]:
import numpy as np

# for i in range(1, 31):
img = cv2.imread('./Open/t01/1.jpg', 0)
img = cv2.resize(img, dsize=(0,0), fx = 0.125, fy = 0.275, interpolation=cv2.INTER_LINEAR)
h = img.shape[0]
w = img.shape[1]
x = int(w/2)
y = int(h/2)

img = img[y-int(h/6):y+int(h/6), x-int(w/3):x+int(w/2)]

cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)
circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,600,
                                param1=50,param2=25,minRadius=140,maxRadius=160)
circles = np.uint16(np.around(circles))

#     if len(circles) == 1:
#         x, y, r = circles[0][0]
# #         print x, y, r
#         mask = np.zeros((img.shape[0],img.shape[1]),dtype=np.uint8)
#         cv2.circle(mask,(x,y),r,(255,255,255),-1,8,0)
# #         cv2.imwrite(argv[2],mask)
#         out = img*mask
#         white = 255-mask
#         cv2.imwrite('./circles_crop2/3rd/{}.png'.format(i),out+white)

for j in circles[0,:]:
    cv2.circle(cimg,(j[0],j[1]),j[2],(0,255,0),2)

cv2.imshow('detected circles',cimg)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
#은근 잘보임
import cv2

image=cv2.imread("./test/18.png")
# image = cv2.resize(image, dsize=(0,0), fx = 0.25, fy = 0.25, interpolation=cv2.INTER_LINEAR)
gray=cv2.GaussianBlur(image,(7,7),0)
# cv2.imshow('GaussianBlur',gray)

#Canny
edged=cv2.Canny(gray,50,50)
edged=cv2.dilate(edged,None,iterations=1)
edged=cv2.erode(edged, None, iterations=1)
cv2.imshow('edged',edged)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [39]:
import cv2
import numpy as np

for i in range(1, 31):
    if(i < 10):
        src = cv2.imread('./Open/t0{}/4.jpg'.format(i))
    else:
        src = cv2.imread('./Open/t{}/4.jpg'.format(i))
    resized = cv2.resize(src, dsize=(0,0), fx = 0.25, fy = 0.25, interpolation=cv2.INTER_LINEAR)

    x, y, r = 515, 376, 350
#     circle = cv2.circle(resized, (x, y), r, (255,255,255), 1)
    # cv2.imshow("img", resized)

    rectX = (x - r) 
    rectY = (y - r)
    # print(rectY+2*r, rectX+2*r)
    crop_img = resized[rectY:rectY+2*r, rectX:rectX+2*r]
#     cv2.imshow("crop", crop_img)
    hsv = cv2.cvtColor(crop_img, cv2.COLOR_BGR2HSV)
    # cv2.imshow("hsv", hsv)
    white_out = cv2.inRange(hsv, (15, 100, 20), (20, 130, 200))
    #white_out = cv2.inRange(hsv, (10, 100, 20), (20, 255, 200))
#     cv2.imshow("white_out", white_out)
    cv2.imwrite('./result2/{}.png'.format(i), white_out)

    cv2.waitKey()
    cv2.destroyAllWindows()

In [4]:
import cv2

src = cv2.imread('./Open/t01/4.jpg')
src = cv2.resize(src, dsize=(0,0), fx = 0.25, fy = 0.25, interpolation=cv2.INTER_LINEAR)

if src is None:
    print('Image load failed!')
    sys.exit()
    
src_hsv = cv2.cvtColor(src, cv2.COLOR_BGR2HSV) # BGR -> HSV 로 변경(색상 검출에 효율적)

# 트랙바 콜백 함수 생성
def on_trackbar(pos):
    hmin = cv2.getTrackbarPos('H_min', 'dst') # 트랙바의 위치를 받아옴 (h_min 값)
    hmax = cv2.getTrackbarPos('H_max', 'dst')
    smin = cv2.getTrackbarPos('S_min', 'dst') # 트랙바의 위치를 받아옴 (h_min 값)
    smax = cv2.getTrackbarPos('S_max', 'dst')
    vmin = cv2.getTrackbarPos('V_min', 'dst') # 트랙바의 위치를 받아옴 (h_min 값)
    vmax = cv2.getTrackbarPos('V_max', 'dst')
    
    dst = cv2.inRange(src_hsv, (hmin, smin, vmin), (hmax, smax, vmax))
    cv2.imshow('dst', dst)
    
cv2.imshow('src', src)
cv2.namedWindow('dst')

# 트랙바 콜백 함수 등록
cv2.createTrackbar('H_min', 'dst', 0, 255, on_trackbar)
cv2.createTrackbar('H_max', 'dst', 0, 255, on_trackbar)
cv2.createTrackbar('S_min', 'dst', 0, 255, on_trackbar)
cv2.createTrackbar('S_max', 'dst', 0, 255, on_trackbar)
cv2.createTrackbar('V_min', 'dst', 0, 255, on_trackbar)
cv2.createTrackbar('V_max', 'dst', 0, 255, on_trackbar)
on_trackbar(0)

cv2.waitKey()

cv2.destroyAllWindows()

TypeError: 'tuple' object is not callable

TypeError: 'tuple' object is not callable

In [42]:
for h in range(19, 21):
    for s in range(101, 255, 5):
        for v in range(21, 200, 5):
            src = cv2.imread('./Open/t01/4.jpg'.format(i))
            resized = cv2.resize(src, dsize=(0,0), fx = 0.25, fy = 0.25, interpolation=cv2.INTER_LINEAR)
            rectX = (x - r)
            rectY = (y - r)
            crop_img = resized[rectY:rectY+2*r, rectX:rectX+2*r]
            hsv = cv2.cvtColor(crop_img, cv2.COLOR_BGR2HSV)
            white_out = cv2.inRange(hsv, (10, 100, 20), (h, s, v))
            cv2.imwrite('./result3/{}{}{}.png'.format(h,s,v), white_out)
            
            cv2.waitKey()
            cv2.destroyAllWindows()

KeyboardInterrupt: 

In [213]:
for i in range(1, 31):
    if(i < 10):
        src = cv2.imread('./Open/t0{}/1.jpg'.format(i))
    else:
        src = cv2.imread('./Open/t{}/1.jpg'.format(i))
    resized = cv2.resize(src, dsize=(0,0), fx = 0.25, fy = 0.25, interpolation=cv2.INTER_LINEAR)
    
    h = resized.shape[0]
    w = resized.shape[1]
    x = int(w/2)
    y = int(h/2)

    resized = resized[y-int(h/7):y+int(h/6), x-int(w/3):x+int(w/2.5)]
    cv2.imwrite('./test/{}.png'.format(i), resized)

    cv2.waitKey()
    cv2.destroyAllWindows()

roi (167, 16, 702, 717)

In [21]:
color = [0, 0, 0]
pixel = np.uint8([[color]])
hsv = cv2.cvtColor(pixel, cv2.COLOR_BGR2HSV)
print(hsv)

color2 = [0, 0, 255]
pixel2 = np.uint8([[color2]])
hsv2 = cv2.cvtColor(pixel2, cv2.COLOR_BGR2HSV)
print(hsv2)

[[[0 0 0]]]
[[[  0 255 255]]]


In [37]:
import numpy as np
import cv2
import os
IMG_DIR = './result'
for img in os.listdir(IMG_DIR):
        img_array = cv2.imread(os.path.join(IMG_DIR,img), cv2.IMREAD_GRAYSCALE)
        img_array = (img_array.flatten())
        img_array  = img_array.reshape(-1, 1).T
        print(img_array)
        with open('output.csv', 'ab') as f:
            np.savetxt(f, img_array, delimiter=",")

[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[  0   0   0 ...   0   0 255]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[  0   0 255 ...   0   0   0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[  0   0   0 ... 255 255 255]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[  0   0   0 ...   0   0 255]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
